"""Canonical inference runtime contracts and ownership boundaries."""

from .admission import AdmissionController, AdmissionRejected
from .contracts import (
    AdmissionDecision,
    AdmissionDisposition,
    BackendFactory,
    BackendHandle,
    BackendKind,
    BackendTurn,
    CapabilityReport,
    GenerationRequest,
    LoadConfig,
    ModelSpec,
    ModelState,
    PreparedBackendHandle,
    PreparedGenerationRequest,
    ProcessState,
    RequestModality,
    RoleName,
    RoleSnapshot,
    RoleSpec,
    RuntimeKey,
)
from .manager import (
    RuntimeCapacityError,
    RuntimeManager,
    RuntimeManagerError,
    RuntimeUnavailableError,
)
from .readiness import ReadinessService
from .role_manifest import (
    ACCEPTED_ROLE_SPECS,
    RoleManifestError,
    RoleManifestSignatureError,
    RoleManifestSource,
    RoleManifestTopologyError,
    SignedRoleManifest,
    canonical_role_manifest_bytes,
    load_role_manifest,
    parse_role_manifest,
    parse_role_manifest_json,
)
from .roles import RoleDirectory, UnknownRoleError
from .service import FirstWriterCancelToken, RuntimeStartError, RuntimeStartService

__all__ = [
    "ACCEPTED_ROLE_SPECS",
    "AdmissionController",
    "AdmissionDecision",
    "AdmissionDisposition",
    "AdmissionRejected",
    "BackendFactory",
    "BackendHandle",
    "BackendKind",
    "BackendTurn",
    "CapabilityReport",
    "FirstWriterCancelToken",
    "GenerationRequest",
    "LoadConfig",
    "ModelSpec",
    "ModelState",
    "PreparedBackendHandle",
    "PreparedGenerationRequest",
    "ProcessState",
    "ReadinessService",
    "RequestModality",
    "RoleDirectory",
    "RoleManifestError",
    "RoleManifestSignatureError",
    "RoleManifestSource",
    "RoleManifestTopologyError",
    "RoleName",
    "RoleSnapshot",
    "RoleSpec",
    "RuntimeCapacityError",
    "RuntimeKey",
    "RuntimeManager",
    "RuntimeManagerError",
    "RuntimeStartError",
    "RuntimeStartService",
    "RuntimeUnavailableError",
    "SignedRoleManifest",
    "UnknownRoleError",
    "canonical_role_manifest_bytes",
    "load_role_manifest",
    "parse_role_manifest",
    "parse_role_manifest_json",
]
